### ISSUE TITLE
Extract DataONEorg/DataPackage class into its own package, 

### ISSUE THREAD

**Issue by ghost** [ropensci/datapackage#1]
DataPackage, SystemMetadata, and probably D1Object would be main classes

- [x] Decide whether to move `SystemMetadata` to `datapackage`
- [x] Create R-based slots for all DataPackage state variables, including systemmetadata, and ORE relationships
- [x] Replace all java-based implementations in `DataPackage` with native R
- [x] Rename `D1Object` to something less DataONE centric
- [x] Replace all java-based implementation in '`D1Object` with native R

**Comment by mbjones** [comment]
DataPackage and DataObject are now standalone S4 classes.  Still need some additional features on these classes, but those will be opened as separate tickets.
