### ISSUE TITLE
standardize on one class initialization mechanism

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapackage#20]
The class "DataPackage" requires this form for object creation:

```
pkg <- DataPackage()
```

Should we standarize on the form used by "DataObject" and only allow object
create through new? 

```
do <- new("DataObject", ...)
```

**Comment by mbjones** [comment]
I think all classes should work with the new() function and initialize().

Sometimes it may also be useful to provide some specific constructors that take certain parameters, but let's evaluate if that is easier than calling new() in each case.

**Comment by sbpcs59** [comment]
Constructors that don't take any parameters will be removed, as all these constructors
are doing is calling new("someclass") and returning the object (e.g. setMethod("DataPackage", signature(), function()). Constructors that do provide an alternative way to create an object will be retained (e.g. setMethod("SystemMetadata", signature("XMLInternalElementNode"), function(sysmeta, ...))

**Comment by sbpcs59** [comment]
Implemented in commit 4d5aacb14da077e18f1de5b6d7ea00c13db08189
