### ISSUE TITLE
Installation errors: the `redland` package is not available

### ISSUE THREAD

**Issue by jjchern** [ropensci/datapackage#29]
I tried to install the package with `devtools::install_github("ropensci/datapackage")`, but got the following errors:

```r
Downloading github repo ropensci/datapackage@master
Installing datapackage
Skipping 1 packages not available: redland
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/m8/68z5d14d7mv9qyf1bd69ych40000gn/T/RtmpQWZ1bF/devtools32b45c3ccb9/ropensci-datapackage-ff07ac0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘redland’ is not available for package ‘datapackage’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/datapackage’
Error: Command failed (1)
```

**Comment by sbpcs59** [comment]
@jjchern Have a look at https://github.com/ropensci/redland-bindings/blob/master/R/redland/README.md for instructions on installing the 'redland'
package. Both packages are 'pre-release' software, so we would much appreciate any
feedback you have on these packages.

**Comment by sbpcs59** [comment]
@jjchen New installation instructions are also available at https://github.com/ropensci/datapackage
