### ISSUE TITLE
Confirm that resource maps created by serializeRDF conform to the DataONE spec

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapackage#38]
The document http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/design/DataPackage.html#generating-resource-maps outlines the requirements
of a resource map submitted to DataONE. Confirm that the resmaps created by datapackage 
conform to this spec, especially D1 identifiers in URIs and in dcterms:identifiers.

**Comment by sbpcs59** [comment]
Updated in commit 1fa175f7f2dcfe079b904d00eeec6180ac4ac3de

**Comment by sbpcs59** [comment]
After this last commit, the resource map identifier is being improperly URLencoded, for example:

```
  <rdf:Description rdf:about="https://cn.dataone.org/cn/v2/resolve/resourceMap_urn%3Auuid%3Ametadata">
    <dcterms:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#string">resourceMap_urn%3Auuid%3Ametadata</dcterms:identifier>
  </rdf:Description>
```

The subject URL is encoded properly, the object should not be

**Comment by sycao5** [comment]
It seems to look like this for me: 

<rdf:Description rdf:about="https://cn.dataone.org/cn/v1/resolve/resourceMap_0571596b-b459-4fbe-900f-b4b91e642e7b.rdf">
<dcterms:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#string">resourceMap_0571596b-b459-4fbe-900f-b4b91e642e7b.rdf</dcterms:identifier>

**Comment by sbpcs59** [comment]
@syscao5 could you post the entire triplet?

**Comment by sycao5** [comment]
```
<rdf:Description rdf:about="https://cn.dataone.org/cn/v1/resolve/resourceMap_0571596b-b459-4fbe-900f-b4b91e642e7b.rdf">
<dcterms:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#string">resourceMap_0571596b-b459-4fbe-900f-b4b91e642e7b.rdf
</dcterms:identifier>
<dc:creator rdf:nodeID="A0"/>
<rdf:type rdf:resource="http://www.openarchives.org/ore/terms/ResourceMap"/><ore:describes rdf:resource="https://cn.dataone.org/cn/v1/resolve/resourceMap_0571596b-b459-4fbe-900f-b4b91e642e7b.rdf#aggregation"/>
<dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2016-02-08T11:13:35.147-06:00</dcterms:modified>
</rdf:Description>
```

**Comment by sbpcs59** [comment]
@syscao5 Yes, I think that looks ok, as there are no characters in your
resource map identifier that require URL encoding when the id appears in the URL, and
no encoding when the id is the object of the dcterms:identifier.

**Comment by sbpcs59** [comment]
With commit 21e31b574bc44db27a022d53436cb2e452d6d75f, the conformance of the resource maps
to the DataONE additional requirements (to the OAI-ORE spec) should be complete

**Comment by sycao5** [comment]
Can you give me an example for a resource map identifier that require URL encoding so that I can try with my example? Many thanks.

**Comment by sbpcs59** [comment]
@syscao5 In R:

```
library(uuid)
resmapId <- sprintf("urn:uuid:%s", UUIDgenerate())
```

The ':' characters should be URL encoded when you serialize the resource map
