### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by scls19fr** [ropensci/datapackage#39]
Hello,

I'm looking for a R library to read DataPackages http://data.okfn.org/doc/data-package
I'm not sure if this package deals with them.
If that's the case, maybe you should put a link to specification.

Kind regards

**Comment by sbpcs59** [comment]
@scls19fr Currently the datapackage R package can create serializations in the 
OAI-ORE package format: https://www.openarchives.org/ore and the BagIt 
format: https://tools.ietf.org/html/draft-kunze-bagit-08.

I've entered an issue to evaluate this packaging format here: https://github.com/ropensci/datapackage/issues/40

**Comment by scls19fr** [comment]
Ok thanks.

Maybe you should put these 2 links (OAI-ORE package format: https://www.openarchives.org/ore and the BagIt format: https://tools.ietf.org/html/draft-kunze-bagit-08 ) in `README.md`

**Comment by sbpcs59** [comment]
@scls19fr Thanks, I'll add the links to the README.md (and the intro vignette).
