### ISSUE TITLE
Update S4 generics so minimal signature is used

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapackage#41]
Use as few arguments in the setGeneric function signature as necessary, provide flexibility
for users that wish to write their own methods that will be dispatched from our generic.

For our own uses, we need to have adequate parameters to dispatch on, so if we have multiple
methods implemented, we may need at least the first param, and sometimes the second, i.e.
addAccessRule(x, y) requires "x" to be able to dispatch to DataObject or SystemMetadata
implementations, "y" is required to dispatch based on a character string containing one access rule
or a data.frame containing possibly multiple access rules.

**Comment by sbpcs59** [comment]
Changed in commit eb67df91caa6081cf96570ea53cbf0393053029c

**Comment by mbjones** [comment]
@sbpcs59 One note -- often, then second dispatch is based on a different logical treatment of the eincoming data, and could be handled by a single method definition with a conditional that fires off different private methods to handle the cases.  I think it should be exceedingly rare that we would need more than one parameter for dispatch -- the rest can and should be handled with local conditionals to keep the generic function simple.

Can you check this too? Thx.

**Comment by sbpcs59** [comment]
@mbjones That appears to be the case for addAccessRule - the first parameter dispatches on
a DataObject or SystemMetadata. The second parameter currently dispatches to handle
either a character containing the first portion of the access rule, or a data.frame containing multiple
rules. Dispatch based on this 2nd parameter could be replaced with testing the class type of the
parameter within the method.

So currently there are 4 methods to addAccessRules:
- setMethod("addAccessRule", signature("DataObject", "character")
- setMethod("addAccessRule", signature("DataObject", "data.frame")
- setMethod("addAccessRule", signature("SystemMetadata", "character"),
- setMethod("addAccessRule", signature("SystemMetadata", "data.frame")

If dispatch is for only DataObject or SystemMetadata, then these four methods could be
collapsed to two.

**Comment by sbpcs59** [comment]
One generic that does require two parameters is addData, as we need the following:

In datapackage R package, we need to support adding "DataObjects" to a package, so the
second argument is needed to dispatch to the datapackage implementation:
```
setGeneric("addData", function(x, do, ...)
setMethod("addData", signature("DataPackage", "DataObject")
```
in dataone R package, we need to dispatch to the implementation that handles
D1Objects for compatibility to the dataone R package v1:

```
setMethod("addData", signature("DataPackage", "D1Object")
```

**Comment by sbpcs59** [comment]
This task was completed with commit 3374f80e93ade81a54df3294e84221a2129b1b20
